runtime: php74 # Replace with php74 to use PHP 7.4
runtime_config:
  document_root: Cloud-Box

handlers:
- url: /.*
  script: auto

# Serve a directory as a static resource.
- url: /css
  static_dir: css


# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

entrypoint: 
  serve handler.php

env_variables:

  CLOUDSQL_USER: root
  CLOUDSQL_DB: userdetail
  CLOUDSQL_PASSWORD: pass213
  CLOUDSQL_DSN: mysql:unix_socket=/cloudsql/bustling-walker-308215:europe-west2:cloud-box-2
# [END gae_cloudsql_mysql_env]
